GET http://localhost:3003/user/2

###
PUT http://localhost:3003/user
Content-Type: application/json

{
   "name":"Nobara Kugisake",
   "nickname": "menina-dos-pregos",
   "email": "nobara_kugisake@jjk.com"
}

